openapi: 3.2.0
info:
  version: 1.0.0
  title: Origami Risk Public New Endpoint API
servers:
- url: https://{environment}.origamirisk.com/OrigamiApi
tags:
- name: New Endpoint
paths:
  /new-endpoint:
    get:
      summary: New Endpoint
      description: This is your first endpoint! Edit this page to start documenting your API.
      operationId: get_new-endpoint
      responses:
        '200':
          description: Successful response
      tags:
      - New Endpoint
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Token
